### ISSUE TITLE
Creative stick keeps rolling itself back.

### ISSUE THREAD

**Issue by andrewkm** [sunkid/CreativeStick#4]
This plugin keeps rolling itself back every time i do a full server backup (I do one once every 1-2 days or so) Where i move the entire server to another backup drive. Afterwards when starting the server the plugin rolls itself back to a previous version which does not load on start up.

I have to re download it from bukkit dev (Latest version) every time and its getting quite annoying now.
- I understand this issue might sound insanely stupid but i promise you I know what im doing and am totally face palming over this lol. Is it possibly downloading itself into a different version thinking its new (yet its grabbing an old version) ? I even tried to totally regenerate a new creative stick folder/config - issue still occurs.

Sigh this is so hard to explain lol I hope you get it :p

**Comment by sunkid** [comment]
Sheesh, I am getting rusty it seems. 

Thanks for pointing this out @andrewkm, it should be fixed now! I forgot to push the latest release to github and CS was indeed re-downloading itself. If you want, you can turn this feature off by adding 'settings.disable-updates: false' in config.yml.

**Comment by andrewkm** [comment]
Thanks for fix :)
